mysql:
  auth:
    rootPassword: "password"
  primary:
    startupProbe:
      enabled: false
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
  secondary:
    replicaCount: 0
