run:
allow-parallel-runners: true
linters:
  enable:
    - nestif
    - funlen
    - lll
    - forcetypeassert
    - gofumpt
    - govet
    - staticcheck
    - revive
    - errorlint
    - exportloopref
    - cyclop
    - unparam
    - unused

linters-settings:
  funlen:
    ignore-comments: true
    lines: 100

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - cyclop
        - lll
