services:
  mailpit:
    image: axllent/mailpit
    healthcheck:
      test: wget --server-response http://localhost:8025/readyz 2>&1 | awk '/^  HTTP/{print $2}' | grep 200
      start_period: 5s
      interval: 3s
      timeout: 3s
      retries: 30
    networks:
      - converter
  vegeta:
    build:
      context: tests
      dockerfile: ./Dockerfile
    image: vegeta
    depends_on:
      - gw
    environment:
      - VEGETA_GW_ADDR=gw:8080
      - VEGETA_PROM_EXPORTER_ADDR=0.0.0.0:8880
    restart: on-failure
    networks:
      - converter

  mailer:
    env_file:
      - .env.test
    networks:
      - converter
