version: "3"

includes:
  gw:
    taskfile: ./gw/taskfile.yaml
    dir: ./gw
  mailer:
    taskfile: ./mailer/taskfile.yaml
    dir: ./mailer
  rw:
    taskfile: ./ratewatcher/taskfile.yaml
    dir: ./ratewatcher
  sub:
    taskfile: ./sub/taskfile.yaml
    dir: ./sub
  protos:
    taskfile: ./protos/taskfile.yaml
    dir: ./protos

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
  lint:
    deps:
      - gw:lint
      - mailer:lint
      - rw:lint
      - sub:lint
  test:
    deps:
      - gw:test
      - mailer:test
      - rw:test
      - sub:test
  test:race:
    deps:
      - gw:test:race
      - mailer:test:race
      - rw:test:race
      - sub:test:race
  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - command -v golangci-lint
