version: "3"

includes:
  gw:
    taskfile: ./gw/taskfile.yaml
    dir: ./gw
  mailer:
    taskfile: ./mailer/taskfile.yaml
    dir: ./mailer
  rw:
    taskfile: ./ratewatcher/taskfile.yaml
    dir: ./ratewatcher
  protos:
    taskfile: ./protos/taskfile.yaml
    dir: ./protos

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
