version: "3"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all

  pre-commit:
    deps: [format, lint, test, pre-commit:install]

  pre-commit:install:
    deps: [pre-commit-tool:install]
    desc: "Install pre-commit into git repository"
    status:
      - test -f .git/hooks/pre-commit
    cmds:
      - pre-commit install

  test:
    desc: "Run all tests"
    deps: [test:race, test:coverage]

  test:race:
    desc: "Run test with the race flag"
    cmds:
      - go test -race -failfast ./...

  test:coverage:
    desc: "Run tests and collect coverage"
    cmds:
      - go test -coverprofile=cover.out ./...

  lint:
    desc: "Run golangci-lint"
    deps: [lint:install]
    cmds:
      - golangci-lint run

  format:
    desc: "Run formatters"
    aliases: [fmt]
    tasks:
      - task: tidy
      - task: fmt:code

  sync-deps:
    desc: "Install missing and clean unused golang deps"
    aliases: [tidy]
    cmds:
      - go mod tidy

  format:code:
    desc: "Format code using go-fumpt"
    aliases: [fmt:code]
    deps: [gofumpt:install]
    cmds:
      - echo "Formatting the code..."
      - gofumpt -w -l .

  install:
    desc: "Install all tools"
    deps: [gofumpt:install, lint:install]

  gofumpt:install:
    desc: "Install gofumpt code formatter for Go"
    status:
      - command gofumpt -version
    cmds:
      - go install mvdan.cc/gofumpt@latest

  golangci-lint:install:
    aliases: [lint:install]
    desc: "Install golangci-lint"
    status:
      - command golangci-lint version
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  pre-commit-tool:install:
    desc: "Install pre-commit tool into system"
    status:
      - command pre-commit help
    cmds:
      - pip3 install pre-commit
