version: "3"

includes:
  gw:
    taskfile: ./gw/taskfile.yaml
    dir: ./gw
  mailer:
    taskfile: ./mailer/taskfile.yaml
    dir: ./mailer
  rw:
    taskfile: ./rw/taskfile.yaml
    dir: ./rw
  sub:
    taskfile: ./sub/taskfile.yaml
    dir: ./sub
  protos:
    taskfile: ./protos/taskfile.yaml
    dir: ./protos

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
  lint:
    cmds:
      - task gw:lint
      - task mailer:lint
      - task rw:lint
      - task sub:lint
  test:
    deps:
      - gw:test
      - mailer:test
      - rw:test
      - sub:test
  test:race:
    deps:
      - gw:test:race
      - mailer:test:race
      - rw:test:race
      - sub:test:race
