version: "3"

includes:
  rw:
    taskfile: ./ratewatcher/taskfile.yaml
    dir: ./ratewatcher
  protos:
    taskfile: ./protos/taskfile.yaml
    dir: ./protos

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
