global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: vegeta
    static_configs:
      - targets:
          - vegeta:8880
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: rw
    scrape_interval: 10s
    static_configs:
      - targets:
          - rw:2112
  - job_name: mailer
    scrape_interval: 10s
    static_configs:
      - targets:
          - mailer:2112
  - job_name: sub
    scrape_interval: 10s
    static_configs:
      - targets:
          - sub:2112
