version: "3"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
  run:
    desc: "Populate env from .env file and run service"
    deps: [install:godotenv]
    cmds:
      - godotenv -f ../.env task run-with-env
  run-with-env:
    required:
      vars:
        - EXCHANGE_API_KEY
        - EXCHANGE_API_BASE_URL
        - EXCHANGE_LOG_LEVEL
        - EXCHANGE_PORT
    cmds:
      - go run ./cmd/server
  format:
    desc: "Run gofumpt"
    deps: [install:gofumpt]
    cmds:
      - echo "Running formatter..."
      - gofumpt -e -l -w .
  lint:
    desc: "Run golangci-lint"
    deps: [install:lint]
    cmds:
      - echo "Running linters..."
      - golangci-lint run
    sources:
      - .golangci.yaml
      - ./**/*.go
      - go.mod
      - go.sum
  test:
    desc: "Run tests"
    cmds:
      - echo "Running tests..."
      - mkdir -p bin
      - go test -coverprofile bin/cover.out ./...
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/cover.out

  test:cover:
    desc: "Run tests & show coverage"
    deps:
      - test
    cmds:
      - go tool cover -func bin/cover.out

  test:race:
    desc: "Run tests with a race flag"
    cmds:
      - go test -race -count=8 -failfast ./...

  test:integration:
    deps: [install:godotenv]
    desc: "Run integration tests"
    cmds:
      - godotenv -f .env.test task test:integration-with-env -- {{ .CLI_ARGS }}

  test:integration-with-env:
    cmds:
      - go test -tags=integration ./... {{ .CLI_ARGS }}

  generate:
    desc: "Generate (used for mock generation)"
    deps: [install:mock]
    cmds:
      - echo "Running generators..."
      - go generate ./...
    sources:
      - ./**/*.go
      - go.mod
      - go.sum

  install:
    desc: "Install all tools"
    deps:
      - install:lint
      - install:gofumpt
      - install:mock

  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - command -v golangci-lint

  install:gofumpt:
    desc: "Install gofumpt"
    cmds:
      - go install mvdan.cc/gofumpt@latest
    status:
      - command -v gofumpt

  install:mock:
    desc: "Install mockgen"
    cmds:
      - go install go.uber.org/mock/mockgen@latest
    status:
      - command -v mockgen
  install:godotenv:
    desc: "Install go dot env lib"
    cmds:
      - go install github.com/joho/godotenv/cmd/godotenv@latest
    status:
      - command godotenv
