apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - orgId: 1
    id: prometheus
    uid: PBFA97CFB590B2093
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
    readOnly: false
