apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sub.fullname" . }}
  labels:
    {{- include "sub.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sub.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: "{{ .Chart.Name}}-wait-for-db"
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "sub.fullname" . }}
          command:
            - "/bin/bash"
            - "-c"
            - | 
              until mysql --host=${MYSQL_HOSTNAME} --user=${MYSQL_USER} \
              --password=${MYSQL_PASSWORD} --execute="SELECT 1;"; do echo "waiting for mysql"; sleep 2; done;

        - name: "{{ .Chart.Name}}-migrate-db"
          image: "golang:latest"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "sub.fullname" . }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              go install -tags "mysql" github.com/golang-migrate/migrate/v4/cmd/migrate@latest && \
              migrate -path="/mnt/database" -database "mysql://$SUB_DSN" up

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "sub.fullname" . }}
            - configMapRef:
                name: {{ include "sub.fullname" . }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
