apiVersion: v1
kind: Service
metadata:
  name: {{ include "sub.fullname" . }}
  labels:
    {{- include "sub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: grpc
  selector:
    {{- include "sub.selectorLabels" . | nindent 4 }}
