swagger: "2.0"
info:
  title: v2/mailer/mailer.proto
  version: version not set
tags:
  - name: MailerService
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  mailerv2Mail:
    type: object
    properties:
      to:
        type: array
        items:
          type: string
      subject:
        type: string
      html:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
