definitions:
  github_com_hrvadl_converter_gw_internal_transport_http_handlers.EmptyResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  github_com_hrvadl_converter_gw_internal_transport_http_handlers.ErrorResponse:
    properties:
      error:
        type: string
      success:
        type: boolean
    type: object
  github_com_hrvadl_converter_gw_internal_transport_http_handlers.Response-float32:
    properties:
      data:
        type: number
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/rate:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hrvadl_converter_gw_internal_transport_http_handlers.Response-float32'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hrvadl_converter_gw_internal_transport_http_handlers.ErrorResponse'
      summary: Get USD -> UAH exchange rate
      tags:
      - Rate
  /api/subscribe:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Email to subscribe
        in: formData
        name: body
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_hrvadl_converter_gw_internal_transport_http_handlers.EmptyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_hrvadl_converter_gw_internal_transport_http_handlers.ErrorResponse'
      summary: Subscribe to email rate exchange notification
      tags:
      - Rate
swagger: "2.0"
