apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gw.fullname" . }}
  labels:
    {{- include "gw.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.configMapData }}
  {{ $key | nindent 2 }}: {{ $value }}
  {{- end }}
