name: CI

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch: {}

jobs:
  integration:
    name: Integration Tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      SUB_TEST_MYSQL_ROOT_PASSWORD: "password"
      SUB_TEST_MYSQL_DATABASE: "converter"
      SUB_TEST_MYSQL_PORT: "33000"
      SUB_TEST_MYSQL_HOSTNAME: "localhost"
      SUB_TEST_DSN: "root:password@(0.0.0.0:33000)/converter?parseTime=true"
      MAILER_TEST_SMTP_PASSWORD: "test test test"
      MAILER_TEST_SMTP_FROM: "hrvadl@gmail.com"
      MAILER_TEST_SMTP_HOST: "0.0.0.0"
      MAILER_TEST_SMTP_PORT: "1025"
      MAILER_TEST_API_PORT: "8025"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Run integration tests
        run: task test:integration-ci -- -p=1
